# .github/workflows/deploy-ssh.yml
##
# Deploy via SSH
##
# This workflow builds the site and deploys it to a server via SSH.
#
# Required Secrets (Settings → Secrets and variables → Actions → Secrets):
#   - SSH_SERVER: The hostname of your SSH server (e.g., example.com)
#   - SSH_USERNAME: Your SSH username
#   - SSH_PRIVATE_KEY: Your SSH private key (the entire key contents)
#
# Required Variables (Settings → Secrets and variables → Actions → Variables):
#   - SITE_URL: The URL where your site will be accessible (e.g., https://example.com)
#   - SSH_SERVER_DIR: The directory on the server to deploy to (e.g., /var/www/html)
#
# Optional Variables (Settings → Secrets and variables → Actions → Variables):
#   - BUILD_COMMAND: The npm command to run for building the site (defaults to "npm run build")
#   - SSH_PORT: The SSH port to use (defaults to "22")
#   - SSH_EXCLUDE: Files to exclude from deployment (comma separated)
#
# To set these up:
#   1. Go to your GitHub repository
#   2. Navigate to Settings → Secrets and variables → Actions
#   3. Add the required secrets in the "Secrets" tab
#   4. Add the required and optional variables in the "Variables" tab
#
# SSH Key Setup:
#   1. Generate an SSH key pair: ssh-keygen -t rsa -b 4096 -C "github-actions"
#   2. Add the public key to your server's ~/.ssh/authorized_keys
#   3. Add the private key contents to the SSH_PRIVATE_KEY secret
##

name: 🚀 Deploy via SSH
run-name: deploy-ssh

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  environment: production

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      # Build the site
      - name: 👷‍♂️ Build the site
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_command: ${{ vars.BUILD_COMMAND || 'npm run build' }}

  deploy:
    # Add a dependency to the build job
    needs: build

    # Deploy to the production environment
    environment:
      name: production

    # Deploy the site via SSH
    runs-on: ubuntu-latest
    steps:
      # Start a deployment
      - name: 🟢 Start Deployment
        id: deployment
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.environment }}

      # Deploy via SSH
      - name: 🚀 Deploy via SSH
        id: ssh_deploy
        uses: ./.github/actions/deploy-ssh
        with:
          artifact_name: public
          artifact_path: public
          ssh_server: ${{ secrets.SSH_SERVER }}
          ssh_username: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_port: ${{ vars.SSH_PORT || '22' }}
          server_dir: ${{ vars.SSH_SERVER_DIR }}
          exclude: ${{ vars.SSH_EXCLUDE }}

      # Set the deployment status to success
      - name: ✅ Finish Deployment
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ vars.SITE_URL }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
