name: '🚀 Deploy via SSH'
description: 'Downloads build artifact and deploys it via SSH'
inputs:
  artifact_name:
    description: 'Name of the artifact to download'
    required: false
    default: 'public'
  artifact_path:
    description: 'Path to extract the artifact to'
    required: false
    default: 'public'
  ssh_server:
    description: 'SSH server hostname'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  server_dir:
    description: 'Server directory to deploy to'
    required: true
  exclude:
    description: 'Files to exclude from deployment (comma separated)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    # Get the artifact from the build job
    - name: 📥 Get artifact
      id: get_artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_path }}
      shell: bash

    # Deploy via SSH
    - name: 🚀 Deploy via SSH
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ inputs.ssh_server }}
        remote-user: ${{ inputs.ssh_username }}
        private-ssh-key: ${{ inputs.ssh_private_key }}
        ssh-port: ${{ inputs.ssh_port }}
        source-path: ${{ inputs.artifact_path }}/
        destination-path: ${{ inputs.server_dir }}
        exclude-list: ${{ inputs.exclude }}
